version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app_ads
    volumes:
      - .:/code/
      - static_volume_ads:/code/static
    networks:
      - main_ads

  nginx:
    container_name: nginx_ads
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume_ads:/code/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main_ads
    restart: always


volumes:
  static_volume_ads:
    external: true
networks:
  main_ads:
    external: true
