# Generated by Django 4.1.5 on 2023-01-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfluextend',
            name='fullname',
            field=models.CharField(max_length=34, unique=True),
        ),
    ]
