# Generated by Django 4.1.5 on 2023-01-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usercompanyextend_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('phone_number', models.CharField(max_length=18)),
                ('subject', models.CharField(max_length=76)),
                ('message', models.TextField()),
            ],
        ),
    ]
