# Generated by Django 4.1.5 on 2023-01-22 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influs', to='core.usercompanyextend')),
                ('influ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.userinfluextend')),
            ],
        ),
    ]
