# Generated by Django 4.1.5 on 2023-01-22 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influs', to='core.usercompanyextend'),
        ),
    ]
